export const apiRoute = {
    login: `${process.env.NEXT_PUBLIC_API_BASE_URL}/auth/login`,
    becomeMerchant: `${process.env.NEXT_PUBLIC_API_BASE_URL}/client/becomeMerchant`,
    addProduct: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/addProduct`,
    getProducts: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/getProducts?pageNumber=1&limit=10`,
    removeProduct: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/deleteProduct`,
    updateProduct: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/updateProduct`,
    getAllProducts: `${process.env.NEXT_PUBLIC_API_BASE_URL}/getProducts?pageNumber=1&limit=10`,
    addToCart: `${process.env.NEXT_PUBLIC_API_BASE_URL}/client/updateCart`,
    cartCount: `${process.env.NEXT_PUBLIC_API_BASE_URL}/client/cartCount`,
    viewCart: `${process.env.NEXT_PUBLIC_API_BASE_URL}/client/viewCart`,
    resetPassword: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/resetPassword`,
    getOrders: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/getOrders`,
    getOrdersCount: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/ordersCount`,
    getTransactionsPerCategory: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/getTransactionsPerCategory`,
    getProductsCount: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/productsCOunt`,
    getTotalIncome: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/totalIncome`,
    getTransactionPerMode: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/transactionPerMode`,
    getWithdrawalsCount: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/withdrawalsCount`,
    getWithdrawals: `${process.env.NEXT_PUBLIC_API_BASE_URL}/merchant/getWithdrawals`,
};
